[package]
name = "typed-event-triggers"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btreemultimap-value-ord = "0.3.1"